### ISSUE TITLE
Error loading labels from messages.properties at reload

### ISSUE THREAD

**Issue by maiconandsilva** [groovyzk/grailszk#7]
When Grails reloads, this error message shows up:

```groovy
2021-11-22 11:46:39.716 ERROR --- [nio-8081-exec-7] org.zkoss.mesg.Messages                  : Message code not found: 27112050 not in pt_BR:[org.zkoss.zul.mesg.MZul, /metainfo/mesg/msgzul]
2021-11-22 11:46:39.716  INFO --- [nio-8081-exec-7] o.z.util.resource.impl.LabelLoaderImpl   : Loading labels for pt_BR
2021-11-22 11:46:39.718 ERROR --- [nio-8081-exec-7] org.zkoss.mesg.Messages                  : 
 
java.lang.IllegalStateException: The resources may not be accessed if they are not currently started
    at org.apache.catalina.webresources.StandardRoot.validate(StandardRoot.java:246)
    at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:212)
    at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:206)
    at org.apache.catalina.core.ApplicationContext.getResource(ApplicationContext.java:538)
    at org.apache.catalina.core.ApplicationContextFacade.getResource(ApplicationContextFacade.java:205)
    at org.apache.catalina.core.StandardContext$NoPluggabilityServletContext.getResource(StandardContext.java:6467)
    at org.zkoss.web.util.resource.ServletLabelLocator.locate0(ServletLabelLocator.java:90)
    at org.zkoss.web.util.resource.ServletLabelLocator.locate(ServletLabelLocator.java:75)
    at org.zkoss.util.resource.impl.LabelLoaderImpl.loadLabels(LabelLoaderImpl.java:260)
    at org.zkoss.util.resource.impl.LabelLoaderImpl.getLabel(LabelLoaderImpl.java:118)
    at org.zkoss.util.resource.impl.LabelLoaderImpl.getLabel(LabelLoaderImpl.java:109)
    at org.zkoss.util.resource.Labels.getLabel(Labels.java:61)
    at org.zkoss.mesg.Messages.getFromBundle(Messages.java:81)
    at org.zkoss.mesg.Messages.getNotFound(Messages.java:105)
    at org.zkoss.mesg.Messages.get(Messages.java:157)
    at org.zkoss.mesg.Messages.get(Messages.java:52)
    at org.zkoss.zul.impl.Utils.addLocaleJS(Utils.java:267)
    at org.zkoss.zul.impl.Utils.outLocaleJavaScript(Utils.java:257)
    at org.zkoss.zul.impl.ZulMessageLoader.load(ZulMessageLoader.java:34)
    at org.zkoss.zk.ui.http.Wpds.outLocaleJavaScript(Wpds.java:283)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.zkoss.zk.ui.http.AbstractExtendlet.invoke(AbstractExtendlet.java:137)
    at org.zkoss.zk.ui.http.WpdExtendlet.write(WpdExtendlet.java:450)
    at org.zkoss.zk.ui.http.WpdExtendlet.access$1700(WpdExtendlet.java:83)
    at org.zkoss.zk.ui.http.WpdExtendlet$WpdContent.toByteArray(WpdExtendlet.java:692)
    at org.zkoss.zk.ui.http.WpdExtendlet$WpdContent.access$400(WpdExtendlet.java:657)
    at org.zkoss.zk.ui.http.WpdExtendlet.retrieve(WpdExtendlet.java:149)
    at org.zkoss.zk.ui.http.WpdExtendlet.service(WpdExtendlet.java:94)
    at org.zkoss.web.util.resource.ClassWebResource.web0(ClassWebResource.java:585)
    at org.zkoss.web.util.resource.ClassWebResource.web(ClassWebResource.java:571)
    at org.zkoss.web.util.resource.ClassWebResource.service(ClassWebResource.java:262)
    at org.zkoss.zk.au.http.DHtmlUpdateServlet.doGet(DHtmlUpdateServlet.java:427)
```

**Comment by maiconandsilva** [comment]
These messages show up because spring-dev-tools is not configured properly. Including Grailszk  and ZK jars to devtools restart classloader solves the problem. See https://github.com/groovyzk/grailszk#spring-boot-dev-tools
